### ISSUE TITLE
Relighting: How to test on my own human images?

### ISSUE THREAD

**Issue by sywei11** [google/neural-light-transport#1]
Hi, Since I want to relight the human image for a given HDRI map, can I test it on my own image data and how? Thanks

**Comment by xiumingzhang** [comment]
Our model needs training with "one-light-a-time (OLAT)" data. After training the model, you may relight the person with an HDRI map by linearly combining the relit "basis images."

**Comment by WangJY06** [comment]
Will the OLAT dataset, or a demo for human images be available soon?

**Comment by zhanghongyong123456** [comment]
> Hi, Since I want to relight the human image for a given HDRI map, can I test it on my own image data and how? Thanks

Hello, have you achieved this? I also want to achieve heavy lighting for portraits. Can you give some suggestions?

**Comment by zhanghongyong123456** [comment]
> Our model needs training with "one-light-a-time (OLAT)" data. After training the model, you may relight the person with an HDRI map by linearly combining the relit "basis images."

Hello, I am a beginner in neural rendering, I hope you can give me some code examples, about light and shadow re-illumination，like this example
![05](https://user-images.githubusercontent.com/48466610/123499957-08a8ed80-d66d-11eb-835e-3b5d381b6e04.png)

**Comment by howardgriffin** [comment]
> > Our model needs training with "one-light-a-time (OLAT)" data. After training the model, you may relight the person with an HDRI map by linearly combining the relit "basis images."
> 
> Hello, I am a beginner in neural rendering, I hope you can give me some code examples, about light and shadow re-illumination，like this example ![05](https://user-images.githubusercontent.com/48466610/123499957-08a8ed80-d66d-11eb-835e-3b5d381b6e04.png)

Have you achieved this?
