### ISSUE TITLE
`data_gen/gen_file_stats.py` does not exist

### ISSUE THREAD

**Issue by JulianKnodt** [google/neural-light-transport#3]
Hi,

I was trying to run NLT on my own dataset, and I found that while trying to run I ran into an error to run gen_file_stats.py, but that file doesn't seem to exist. How can I generate Data Status w/o it or where does the file exist?

Thanks!

Edit: I see that `postproc.py` actually does this, but it might be worth updating the error msg.

**Comment by xiumingzhang** [comment]
Hi Julian,

Thanks for raising this issue.

What you should use to generate the "file stats" JSON is this file:
https://github.com/google/neural-light-transport/blob/37b1270ba5121cce5f1771d961e62917b6c5e219/data_gen/postproc.py

I believe it was the error message in the dataset file that misled you, and I've updated the error message to point to this correct file instead.

Thanks, and please feel free to re-open this issue if this doesn't solve the problem.
