### ISSUE TITLE
Is it possible to run in WIN  and how to run nlt_test.py

### ISSUE THREAD

**Issue by zhanghongyong123456** [google/neural-light-transport#4]
1. I want to run the nlt_test.py code. I don't know how to specify the CKPT path，
Can I just specify the path
![10](https://user-images.githubusercontent.com/48466610/123074628-0f0b4f80-d44a-11eb-936a-f8672614d464.png)
2. I don't quite understand how CKPT-30 and CKPT-10 are used. Could you give me a demo
![11](https://user-images.githubusercontent.com/48466610/123074994-627d9d80-d44a-11eb-8064-4eb7d571a378.png)
3. If the realization of custom characters in the new scene of the image synthesis, how to achieve, I hope you can give some advice
I hope to receive your prompt reply. Thank you.

**Comment by xiumingzhang** [comment]
Hi, I don't quite get your questions. Could you please be more specific about your questions?

**Comment by zhanghongyong123456** [comment]
> Hi, I don't quite get your questions. Could you please be more specific about your questions?

Running this project in Win10 prompts me to have this problem
![20](https://user-images.githubusercontent.com/48466610/123354704-beedd380-d596-11eb-8bbc-4c28996637fa.png)

**Comment by xiumingzhang** [comment]
Thanks for the screenshot. 

This is just the logger of xiuminglib, so you can simply disable the logger, e.g., by commenting off all of the logger lines. This shouldn't impede the actual functionality.

That said, I've never run xiuminglib on a Windows system, so I can't say for sure that everything else would work after you comment the logger lines. 

Hope this is helpful. Feel free to reopen and send in more questions, if any.

**Comment by zhanghongyong123456** [comment]
> Thanks for the screenshot.
> 
> This is just the logger of xiuminglib, so you can simply disable the logger, e.g., by commenting off all of the logger lines. This shouldn't impede the actual functionality.
> 
> That said, I've never run xiuminglib on a Windows system, so I can't say for sure that everything else would work after you comment the logger lines.
> 
> Hope this is helpful. Feel free to reopen and send in more questions, if any.
I refer to your test command and specify my own command, the result is like this, I am not sure how to use your test module, I am very confused about it, I hope you can give me some advice
![21](https://user-images.githubusercontent.com/48466610/123360038-b9e15200-d59f-11eb-8ff9-86df419f450a.png)

**Comment by xiumingzhang** [comment]
The screenshot you provided seems to suggest that you'd need to replace all Unix `/`s with the Windows `\`. It'd be the easiest if you get a Unix machine and run our code there. There might be other issues even if you resolve this "slash vs. backslash" problem.

**Comment by zhanghongyong123456** [comment]
> The screenshot you provided seems to suggest that you'd need to replace all Unix `/`s with the Windows `\`. It'd be the easiest if you get a Unix machine and run our code there. There might be other issues even if you resolve this "slash vs. backslash" problem.

Thank you. I'll try it with Ubuntu
