### ISSUE TITLE
When I run the nlt_test.py script, this error appears, I am not sure what the error is,

### ISSUE THREAD

**Issue by zhanghongyong123456** [google/neural-light-transport#5]
![01](https://user-images.githubusercontent.com/48466610/123394678-f9c12d00-d5d1-11eb-9431-cc6b6d15b7c0.png)
![02](https://user-images.githubusercontent.com/48466610/123394687-fc238700-d5d1-11eb-987f-b89f79697def.png)
My code modification is like this
![03](https://user-images.githubusercontent.com/48466610/123395026-545a8900-d5d2-11eb-9ff4-228df2ce1815.png)
I refer to the dragon_specular.ini format and create the checkpoints.ini file myself
![04](https://user-images.githubusercontent.com/48466610/123395895-478a6500-d5d3-11eb-9da5-e464a519f7f4.png)

**Comment by xiumingzhang** [comment]
This seems like a CUDA or cuDNN issue. Does your system have cuDNN and CUDA installed?

**Comment by zhanghongyong123456** [comment]
> This seems like a CUDA or cuDNN issue. Does your system have cuDNN and CUDA installed?

Yes, it is a cuda and cudnn version issue, thank you for your suggestions
